apiVersion: v1
kind: Namespace
metadata:
  name: chime

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chime
  namespace: chime
  labels:
    app: chime
spec:
  replicas: 15
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: chime
  template:
    metadata:
      labels:
        app: chime
    spec:
      containers:
      - image: docker.pkg.github.com/codeforphilly/chime/penn-chime:1.1.0
        name: chime
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: chime
  namespace: chime
  labels:
    app: chime
spec:
  selector:
    app: chime
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000
