name: Publish GitBook to GH Pages

on:
  push:
    branches:
      - 'develop'


jobs:
  gh-pages-projection:
    runs-on: ubuntu-latest
    steps:
    - name: Initialize Chef Habitat artifacts cache directory
      run: |
        sudo mkdir -p /hab/cache/artifacts
        sudo chown runner:docker -R /hab
    - name: Cache Chef Habitat artifacts
      uses: actions/cache@v1
      with:
        path: /hab/cache/artifacts
        key: hab-cache-artifacts
    - name: 'Update holobranch: gh-pages'
      uses: JarvusInnovations/hologit@actions/projector/v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HAB_LICENSE: accept
      with:
        ref: develop
        holobranch: gh-pages
        commit-to: gh-pages
